name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  determine-affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get affected projects
        id: affected
        uses: soda-digital/dotnet-affected-action@v1.0.1
        with:
          from: ${{ github.event.pull_request.base.sha || github.event.before }}
          to: ${{ github.event.pull_request.head.sha || github.sha }}

  build-and-test:
    needs: determine-affected
    if: ${{ needs.determine-affected.outputs.affected != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build affected projects
        run: dotnet build ${{ fromJson(needs.determine-affected.outputs.affected).join(' ') }} --configuration Release
      - name: Test affected projects
        run: dotnet test ${{ fromJson(needs.determine-affected.outputs.affected).join(' ') }} --configuration Release
